<value> ::= <string> | <number> | <object> | <array> | true | false | null
<object> ::= "{" [ <object_keys> { , <object_keys> } ] "}"
<object_keys> ::= <not empty string> : <value>
<array> ::= "["  [ <value> { , <value> } ] "]" 
<number> ::= [ - ] ( 0 | ( <digit 1-9> { <digit> } ) ) [ . <digit> { <digit> } ] [ ( e | E ) [ + | - ] <digit> { <digit> } ]
<not empty string> ::= ( '"' ( <char content string> { <char content string> } ) '"' ) | ( "'" ( <char content string> { <char content string> } ) "'" ) 
<char content string> ::=  <Any UNICODE CHARACTER except " or \\ or control character> | ( \ ( "'" | \ | / b f n r t ( u <4 decimal> ) )

<string> ::= ( '"' { <char content string> } '"' ) | ( "'" { <char content string> } "'" ) 

<digit> ::= 0 | <digit 1-9> 
<digit 1-9> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<Any UNICODE CHARACTER except " or \\ or control character> ::= a | b c d e f g h i j k l m n o p k r s t u v w x y z
<4 decimal> ::= <digit> <digit> <digit> <digit>
